trigger:
  batch: true
  branches:
    include:
    # - master
    # - dev
    - EES-3976-migrate-to-PNPM
  paths:
    include:
    - infrastructure/*
    exclude:
    - README.md
pr: EES-3976-migrate-to-PNPM

pool:
  vmImage: 'windows-latest'

steps:
- task: AzSKARMTemplateChecker@4
  enabled: false
  inputs:
    ARMTemplateFilePath: '$(System.DefaultWorkingDirectory)/infrastructure/templates/'
    ARMTemplateParameterFilePath: '$(System.DefaultWorkingDirectory)/infrastructure/parameters/'
    SkipControlsFromFile: '$(System.DefaultWorkingDirectory)/infrastructure/template-checker/skip-controls.csv'
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'arm-template'
    targetPath: 'infrastructure'