name: Validate snapshots
on:
  workflow_dispatch:
  schedule: 
    - cron: '30 9 * * 1-5'
env:
  PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  PYTHON_VERSION: 3.10.10
  DATE: $(date --rfc-3339=date)


jobs:
  test:
    name: Validate snapshots
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Install moreutils
        run: sudo apt install moreutils

      # https://github.com/actions/virtual-environments/issues/1187
      - name: tune linux network
        run: sudo ethtool -K eth0 tx off rx off            

      - name: checkout
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pipenv'

      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python

      - name: pipenv install
        run: pipenv install

      - name: echo stuff to file
        working-directory: tests/robot-tests/tests/snapshots
        run: echo "yo yo yo " >> test.txt

      - name: Validate snapshots
        working-directory: tests/robot-tests
        run: pipenv run python scripts/create_snapshots.py --validate --slack-webhook-url ''

      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ env.PAT_TOKEN }}
          commit-message: 'chore(tests): update test snapshots - ${{ env.DATE }}'
          committer: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch-suffix: timestamp
          branch: chore/update-test-snapshots
          add-paths: |
            tests/robot-tests/tests/snapshots
          # reviewers: rmbielby, lauraselby, cjrace, chfoster, twilliams24
          title: 'Update test snapshots ${{ env.DATE }}'
          body: |
            ## Updated test snapshots due to visual differences ${{ env.DATE }}
          draft: false
